### ISSUE TITLE
what exact dataset did you use in MTL - bioinformatics-2016?

### ISSUE THREAD

**Issue by Jimin9401** [cgmhaicenter/exBERT#6]
Hello! I research the performance of models regarding with domain adaptation in NLP ( sciBERT, BioBERT, FinBERT, DAPT..)

what exact data did you report in MTL-bioinformatics-2016? 

Thank you

sincerely

**Comment by taiwen97** [comment]
Hi, actually we used three dataset of the MTL-bioinformatics-2016 then average the scores
1. BC5CDR-IOB
2. BioNLP09-IOB
3. NCBI-disease-IOB

Thanks!
